site_name: ToastAnalytics Guide
theme: readthedocs

docs_dir: docs
site_dir: docs
pages:
- ['index.md', '소개', 'Welcome to Toast Analytics']

- ['Developer/1. Getting Started.md', '운영 가이드', '시작하기']
- ['Developer/2. Campaign Guide.md', '운영 가이드', '캠페인 가이드']
- ['Developer/3. Promotion Guide.md', '운영 가이드', 'PROMOTION 가이드']

- ['Developer/4. Android Developer Guide.md', '개발자 가이드', 'Android 개발자 가이드']
- ['Developer/5. iOS Developer Guide.md', '개발자 가이드', 'iOS 개발자 가이드']
- ['Developer/6. Unity Developer Guide.md', '개발자 가이드', 'Unity 개발자 가이드']
- ['Developer/7. Campaign Developer Guide.md', '개발자 가이드', '캠페인 개발자 가이드']
- ['Developer/8. Promotion Developer Guide.md', '개발자 가이드', 'PROMOTION 개발자 가이드']
- ['Developer/9. Error Code.md', '개발자 가이드', 'API 반환값']
- ['Developer/10. Release Notes.md', '개발자 가이드', '릴리즈노트']

- ['FAQ/FAQ.md', 'FAQ', 'FAQ']



