site_name: ToastAnalytics Guide
theme: readthedocs

docs_dir: docs
site_dir: docs

pages:
- ['index.md', 'Introduction', 'Welcome to Toast Analytics']

- ['Developer/1. Getting Started.md', 'Operator Guide', 'Getting Started']
- ['Developer/2. Campaign Guide.md', 'Operator Guide', 'Campaign']
- ['Developer/3. Promotion Guide.md', 'Operator Guide', 'Promotion']
- ['Developer/3. marketing Guide.md', 'Operator Guide', 'Marketing']

#- ['Developer/4. Android Developer Guide.md', 'Developer Guide', 'Android']
- ['https://github.nhnent.com/TOASTCloud/DOCUMENT/blob/master/docs/Analytics/App%20Analytics/iOS%20Developer%60s%20Guide.md', 'Developer Guide', 'Android']
- ['Developer/5. iOS Developer Guide.md', 'Developer Guide', 'iOS']
- ['Developer/6. Unity Developer Guide.md', 'Developer Guide', 'Unity']
- ['Developer/7. Campaign Developer Guide.md', 'Developer Guide', 'Campaign']
- ['Developer/8. Promotion Developer Guide.md', 'Developer Guide', 'Promotion']
- ['Developer/9. Error Code.md', 'Developer Guide', 'Error code']
#- ['Developer/10. Release Notes.md', 'Developer Guide', 'Release Notes']

- ['FAQ/Getting started.md', 'FAQ', 'Getting started']   
- ['FAQ/SDK.md', 'FAQ', 'SDK 적용']

- ['UserGuide/1. Guide_Getting Started.md', '교육자료', 'Getting started']
- ['UserGuide/2. How to Analysis.md', '교육자료', '지표 분석 및 활용']
- ['UserGuide/3. SDK.md', '교육자료', 'SDK적용 유의 사항']
- ['UserGuide/4. In App Campaign.md', '교육자료', '인앱 캠페인']
- ['UserGuide/5. Marketing Tracking.md', '교육자료', '마케팅 트랙킹']








