site_name: ToastAnalytics Guide
theme: readthedocs

docs_dir: docs
site_dir: docs
pages:
- ['index.md', 'Introduction', 'Welcome to Toast Analytics']

- ['Developer/1. Getting Started.md', 'Operator Guide', 'Getting Started']
- ['Developer/2. Campaign Guide.md', 'Operator Guide', 'Campaign Guide']
- ['Developer/3. Promotion Guide.md', 'Operator Guide', 'Promotion Guide']

- ['Developer/4. Android Developer Guide.md', 'Developer Guide', 'Android Developer Guide']
- ['Developer/5. iOS Developer Guide.md', 'Developer Guide', 'iOS Developer Guide']
- ['Developer/6. Unity Developer Guide.md', 'Developer Guide', 'Unity Developer Guide']
- ['Developer/7. Campaign Developer Guide.md', 'Developer Guide', 'Campaign Developer Guide']
- ['Developer/8. Promotion Developer Guide.md', 'Developer Guide', 'Promotion Developer Guide']
- ['Developer/9. Error Code.md', 'Developer Guide', 'API Return Code']
- ['Developer/10. Release Notes.md', 'Developer Guide', 'Release Notes']

- ['FAQ/FAQ.md', 'FAQ', 'FAQ']



